# Generated by Django 5.1 on 2024-08-13 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_alter_imagemodel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemodel',
            name='image',
            field=models.ImageField(upload_to='uploads/'),
        ),
    ]
