# Generated by Django 5.1 on 2024-08-13 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_alter_imagemodel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemodel',
            name='image',
            field=models.ImageField(storage='storages.backends.s3boto3.S3Boto3Storage', upload_to='uploads/'),
        ),
    ]
