# Generated by Django 5.1 on 2024-08-14 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_alter_imagemodel_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImageModel',
        ),
    ]
